# Generated by Django 5.1.1 on 2026-02-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('unidades_por_caja', models.IntegerField(default=1)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_mayor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('poliza', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('stock_critico', models.IntegerField(default=10)),
                ('stock_bajo', models.IntegerField(default=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición'), ('eliminacion', 'Eliminación')], max_length=20)),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Historial de Producto',
                'verbose_name_plural': 'Historiales de Productos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('comentario', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='danados/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Producto Dañado',
                'verbose_name_plural': 'Productos Dañados',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
