# Generated by Django 5.1.1 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodanado',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productodanado',
            name='cantidad_recuperada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productodanado',
            name='cantidad_repuesta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productodanado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
    ]
