# Generated by Django 5.1.1 on 2026-02-28 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_contenedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='contenedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductoContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad de este producto que llegó en este contenedor', verbose_name='Cantidad en este contenedor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_contenedores', to='productos.contenedor', verbose_name='Contenedor')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_contenedores_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_contenedores', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto en Contenedor',
                'verbose_name_plural': 'Productos en Contenedores',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'contenedor')},
            },
        ),
    ]
