# Generated by Django 5.1.1 on 2026-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_contenedor_stock_remove_producto_contenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock principal del producto'),
        ),
    ]
