# Generated by Django 4.2.7 on 2026-03-08 14:40

from django.db import migrations, models


def migrar_cantidad_a_cantidad_recibida(apps, schema_editor):
    """
    Copia el valor actual de 'cantidad' a 'cantidad_recibida' para todos los registros existentes.
    Esto preserva el registro histórico de cuánto llegó originalmente en cada contenedor.
    """
    ProductoContenedor = apps.get_model('productos', 'ProductoContenedor')
    
    # Actualizar todos los registros existentes
    for pc in ProductoContenedor.objects.all():
        pc.cantidad_recibida = pc.cantidad
        pc.save(update_fields=['cantidad_recibida'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_stock_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocontenedor',
            name='cantidad_recibida',
            field=models.IntegerField(default=0, help_text='Cantidad original que llegó en este contenedor (registro histórico)', verbose_name='Cantidad recibida'),
        ),
        migrations.AlterField(
            model_name='productocontenedor',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Cantidad actualmente disponible en este contenedor', verbose_name='Cantidad disponible'),
        ),
        # Migrar datos existentes
        migrations.RunPython(migrar_cantidad_a_cantidad_recibida, reverse_code=migrations.RunPython.noop),
    ]
