# Generated by Django 5.1.1 on 2026-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aumento_mayor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aumento_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'configuracion_precios',
                'verbose_name_plural': 'configuracion_precios',
            },
        ),
    ]
