# Generated by Django 5.1.1 on 2026-03-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('USD', 'Dólar'), ('BOB', 'Boliviano')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
            },
        ),
    ]
