# Generated by Django 5.1.1 on 2026-04-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0002_fix_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocambio',
            name='contexto',
            field=models.CharField(choices=[('general', 'Sistema General'), ('tienda_principal', 'Tienda Principal')], default='general', max_length=30),
        ),
    ]
