# Generated by Django 5.1.1 on 2026-02-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido Recibido'), ('traspaso', 'Estado de Traspaso'), ('stock_critico', 'Stock Crítico'), ('stock_bajo', 'Stock Bajo'), ('venta', 'Venta Recibida'), ('producto_creado', 'Producto Creado'), ('producto_editado', 'Producto Editado'), ('producto_eliminado', 'Producto Eliminado'), ('precio_modificado', 'Precio Modificado'), ('general', 'General')], max_length=20),
        ),
    ]
