# Generated by Django 5.1.1 on 2026-02-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('devolucion', 'Devolución')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='traspasos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_recibidos', to='usuarios.perfilusuario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_enviados', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Traspaso',
                'verbose_name_plural': 'Traspasos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='traspasos.traspaso')),
            ],
            options={
                'verbose_name': 'Detalle de Traspaso',
                'verbose_name_plural': 'Detalles de Traspasos',
            },
        ),
    ]
