# Generated by Django 5.1.1 on 2026-02-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock'),
        ('traspasos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traspaso',
            name='fecha_aceptacion',
        ),
        migrations.AddField(
            model_name='traspaso',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_aceptados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traspaso',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traspaso',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('transito', 'En Tránsito'), ('recibido', 'Recibido'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='detalletraspaso',
            unique_together={('traspaso', 'producto')},
        ),
    ]
