# Generated by Django 5.1.1 on 2026-02-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Tienda')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('sucursal', 'Sucursal'), ('punto_venta', 'Punto de Venta')], default='sucursal', max_length=20, verbose_name='Tipo de Tienda')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas GPS')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Horario de Cierre')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('remodelacion', 'En Remodelación')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='almacenes.almacen', verbose_name='Almacén')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'tiendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
