# Generated by Django 5.1.1 on 2026-02-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='area_m2',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='horario_cierre',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='telefono',
        ),
    ]
