# Generated by Django 5.1.1 on 2026-02-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='almacen',
        ),
    ]
