# Generated by Django 5.1.1 on 2026-02-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0002_remove_deposito_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='area_m2',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='horario_cierre',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='telefono',
        ),
    ]
