# Generated by Django 5.1.1 on 2026-02-13 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('tiendas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='almacenes.almacen'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre_ubicacion',
            field=models.CharField(blank=True, help_text='Nombre de la tienda/almacén/depósito', max_length=200, null=True),
        ),
    ]
