# Generated by Django 5.1.1 on 2026-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_almacen_perfilusuario_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('almacen', 'Almacén'), ('tienda', 'Tienda'), ('tienda_online', 'Tienda Online')], max_length=20),
        ),
    ]
