# Generated by Django 5.1.1 on 2026-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('almacen', 'Almacén'), ('tienda', 'Tienda'), ('deposito', 'Depósito'), ('tienda_online', 'Tienda Online')], max_length=20),
        ),
    ]
