# Generated by Django 5.1.1 on 2026-02-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='capacidad_m2',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='capacidad_productos',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='pais',
        ),
    ]
