# Generated by Django 5.1.1 on 2026-08-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0011_contenedor_descripcion'),
        ('usuarios', '0005_alter_perfilusuario_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('anulacion_venta', 'Anulación de Venta'), ('devolucion', 'Devolución'), ('traspaso_salida', 'Traspaso - Salida'), ('traspaso_entrada', 'Traspaso - Entrada'), ('pedido_recibido', 'Pedido Recibido'), ('danado', 'Producto Dañado'), ('edicion_manual', 'Edición Manual'), ('entrada_contenedor', 'Entrada desde Contenedor')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Positivo = entrada de stock, Negativo = salida de stock', verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(help_text='Cantidad disponible ANTES del movimiento', verbose_name='Stock Anterior')),
                ('stock_actual', models.IntegerField(help_text='Cantidad disponible DESPUÉS del movimiento', verbose_name='Stock Actual')),
                ('referencia', models.CharField(blank=True, help_text='Código de la venta, traspaso, pedido u operación que generó este movimiento', max_length=100, null=True, verbose_name='Referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='productos.producto', verbose_name='Producto')),
                ('ubicacion', models.ForeignKey(help_text='Almacén, tienda o depósito donde ocurrió el movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='usuarios.perfilusuario', verbose_name='Ubicación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'movimientos_stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
