# Generated by Django 5.1.1 on 2026-03-05 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en valor monetario (solo para tiendas)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='amortizacioncredito',
            name='comprobante',
            field=models.ImageField(help_text='Fotografía del comprobante de amortización (obligatoria)', upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudAnulacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(help_text='Motivo de la solicitud de anulación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentario_respuesta', models.TextField(blank=True, null=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_anulacion_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_anulacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_anulacion', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Anulación de Venta',
                'verbose_name_plural': 'Solicitudes de Anulación de Ventas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
