# Generated by Django 5.1.1 on 2026-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizacioncredito',
            name='moneda',
            field=models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', help_text='Moneda en la que se realiza la amortización', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='moneda',
            field=models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', help_text='Moneda en la que se realizó la venta', max_length=10),
        ),
    ]
