# Generated by Django 5.1.1 on 2026-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_amortizacioncredito_moneda_venta_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Tipo de cambio USD/BOB usado en la venta', max_digits=10),
        ),
    ]
