# Generated by Django 5.1.1 on 2026-03-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_tipo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_cajas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('mayor', 'Mayor')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_vendedor',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('almacen', 'Almacén'), ('tienda', 'Tienda'), ('deposito', 'Depósito')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_tipo',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('fijo', 'Monto fijo'), ('porcentaje', 'Porcentaje')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor original del descuento ingresado por el usuario', max_digits=10),
        ),
    ]
