# Generated by Django 5.1.1 on 2026-08-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='comision_transporte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión de transporte (si aplica)', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_comision_transporte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de comisión de transporte (si aplica)', max_digits=10),
        ),
    ]
