# Generated by Django 5.1.1 on 2026-08-19 03:07

from django.db import migrations, models


def inicializar_desglose_pago(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    Venta.objects.filter(tipo_pago='contado').update(monto_efectivo=models.F('total'))


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_sesioncaja_monto_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('Qr', 'Pago QR'), ('Mixto', 'Mixto')], default='contado', max_length=20),
        ),
        migrations.RunPython(inicializar_desglose_pago, migrations.RunPython.noop),
    ]
