# Generated by Django 5.1.1 on 2026-02-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Tienda Virtual')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('url', models.URLField(max_length=300, unique=True, verbose_name='URL de la Tienda')),
                ('dominio', models.CharField(max_length=200, verbose_name='Dominio')),
                ('plataforma', models.CharField(choices=[('propia', 'Plataforma Propia'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('magento', 'Magento'), ('prestashop', 'PrestaShop'), ('otra', 'Otra')], default='propia', max_length=20, verbose_name='Plataforma')),
                ('version_plataforma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión de Plataforma')),
                ('servidor_hosting', models.CharField(blank=True, max_length=200, null=True, verbose_name='Servidor de Hosting')),
                ('certificado_ssl', models.BooleanField(default=True, verbose_name='Certificado SSL')),
                ('email_soporte', models.EmailField(max_length=254, verbose_name='Email de Soporte')),
                ('email_ventas', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Ventas')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('facebook_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Twitter')),
                ('moneda', models.CharField(default='COP', max_length=10, verbose_name='Moneda')),
                ('idioma', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona Horaria')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('desarrollo', 'En Desarrollo')], default='desarrollo', max_length=20, verbose_name='Estado')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_virtuales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tienda Virtual',
                'verbose_name_plural': 'Tiendas Virtuales',
                'db_table': 'tiendas_virtuales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
